### ISSUE TITLE
ImportError: No module named '__init__'

### ISSUE THREAD

**Issue by region51** [barrust/Wikipedia#1]
@barrust 
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from wikipedia import __init__
  File "/builddir/build/BUILD/Wikipedia-1.4.2/wikipedia/__init__.py", line 1, in <module>
    from .wikipedia import *
  File "/builddir/build/BUILD/Wikipedia-1.4.2/wikipedia/wikipedia.py", line 8, in <module>
    import __init__
ImportError: No module named '__init__'
```
?

**Comment by barrust** [comment]
What OS and python version are you running?

**Comment by region51** [comment]
_Fedora 23, python3-3.4.3-6.fc23.x86_64_

**Comment by region51** [comment]
@barrust also tests

```
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing requirements to wikipedia.egg-info/requires.txt
writing dependency_links to wikipedia.egg-info/dependency_links.txt
writing wikipedia.egg-info/PKG-INFO
writing top-level names to wikipedia.egg-info/top_level.txt
reading manifest file 'wikipedia.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wikipedia.egg-info/SOURCES.txt'
running build_ext
search_test (unittest.loader._FailedTest) ... ERROR
page_test (unittest.loader._FailedTest) ... ERROR
test_lang (tests.lang_test.TestLang) ... ok
geosearch_test (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: search_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: search_test
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/Wikipedia-1.4.1/tests/search_test.py", line 7, in <module>
    from request_mock_data import mock_data
ImportError: No module named 'request_mock_data'
======================================================================
ERROR: page_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: page_test
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/Wikipedia-1.4.1/tests/page_test.py", line 6, in <module>
    from request_mock_data import mock_data
ImportError: No module named 'request_mock_data'
======================================================================
ERROR: geosearch_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: geosearch_test
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/Wikipedia-1.4.1/tests/geosearch_test.py", line 8, in <module>
    from request_mock_data import mock_data
ImportError: No module named 'request_mock_data'
----------------------------------------------------------------------
Ran 4 tests in 0.001s
FAILED (errors=3
```)

**Comment by barrust** [comment]
The first issue is due to wanting to get the __version__ property from the __init__.py file. I can revert that back to the other method and still get that which *should* fix that problem. It will be a day before I can get to it. 

The second is odd since I have never tried running the tests that way. I always ran them by going to the changing to the tests folder and using 
``` bash runtests ```
I will also look into this in the next few days.

**Comment by region51** [comment]
>The second is odd since I have never tried running the tests that way.

_Fedora packages_=_python-wikipedia.spec_
```
%check
%{__python2} setup.py test
%{__python3} setup.py test
```

**Comment by region51** [comment]
@barrust https://github.com/goldsmith/Wikipedia/pull/121

**Comment by barrust** [comment]
#2 should resolve both of these issues. I changed the way we store and get version information and added the test_suite option to setup.py Tested on python 2.7 and 3.4
