### ISSUE TITLE
Issues running tests

### ISSUE THREAD

**Issue by mcpat1993** [barrust/Wikipedia#5]
Hi I receive the following when I do bash runtests and I was wondering how to mediate this:

E.EE
======================================================================
ERROR: geosearch_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: geosearch_test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/Patrick/Documents/workspace/quesgenTFIDF/Wikipedia/tests/geosearch_test.py", line 8, in <module>
    from .request_mock_data import mock_data
ValueError: Attempted relative import in non-package

======================================================================
ERROR: page_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: page_test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/Patrick/Documents/workspace/quesgenTFIDF/Wikipedia/tests/page_test.py", line 6, in <module>
    from .request_mock_data import mock_data
ValueError: Attempted relative import in non-package

======================================================================
ERROR: search_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: search_test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/Patrick/Documents/workspace/quesgenTFIDF/Wikipedia/tests/search_test.py", line 7, in <module>
    from .request_mock_data import mock_data
ValueError: Attempted relative import in non-package

----------------------------------------------------------------------

**Comment by barrust** [comment]
Interesting. I can confirm that running the tests using the bash script errors. Can you try the alternate method and see if this works: 
```python setup.py test```

**Comment by mcpat1993** [comment]
Thanks for the reply. I needed write permission where I had it so a `sudo python setup.py test` resulted in
Ran 32 tests in 0.007s

OK

**Comment by barrust** [comment]
Perfect. I will update the docs.

**Comment by barrust** [comment]
Docs updated to use the ```python setup.py test``` method of running the tests.
